# Generated by Django 4.0.1 on 2022-02-01 08:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_blog_category_comment_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('isAndroidApp', models.BooleanField(default=False)),
                ('isIOSApp', models.BooleanField(default=False)),
                ('isFlutterApp', models.BooleanField(default=False)),
                ('isWebsite', models.BooleanField(default=False)),
                ('playStoreLink', models.URLField(null=True)),
                ('appStoreLink', models.URLField(null=True)),
                ('websiteLink', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='theme.portfoliocategory')),
            ],
        ),
    ]
